import type { TarotCard } from '@/types';

// ============================================================
// Major Arcana (22장)
// ============================================================
const MAJOR_ARCANA: TarotCard[] = [
  {
    id: 'major-0',
    name: 'The Fool',
    korName: '바보',
    arcana: 'major',
    number: 0,
    normalMeaning: 'New beginnings, spontaneity, and a leap of faith into the unknown.',
    reverseMeaning: 'Recklessness, poor judgment, and fear of taking a necessary risk.',
    keywords: ['new beginnings', 'freedom', 'spontaneity'],
    korNormalMeaning: '새로운 시작과 즉흥성, 미지의 세계로 내딛는 용기를 뜻합니다.',
    korReverseMeaning: '무모함과 잘못된 판단, 필요한 위험을 회피하려는 두려움을 나타냅니다.',
    korKeywords: ['새로운 시작', '자유', '즉흥성'],
  },
  {
    id: 'major-1',
    name: 'The Magician',
    korName: '마법사',
    arcana: 'major',
    number: 1,
    normalMeaning: 'Resourcefulness, willpower, and the ability to turn ideas into reality.',
    reverseMeaning: 'Manipulation, untapped talent, or poorly planned actions.',
    keywords: ['manifestation', 'willpower', 'resourcefulness'],
    korNormalMeaning: '수완과 의지력, 아이디어를 현실로 만드는 능력을 보여줍니다.',
    korReverseMeaning: '조작이나 미숙한 재능, 계획 없이 벌인 행동을 의미합니다.',
    korKeywords: ['실현', '의지력', '수완'],
  },
  {
    id: 'major-2',
    name: 'The High Priestess',
    korName: '여사제',
    arcana: 'major',
    number: 2,
    normalMeaning: 'Intuition, hidden knowledge, and trust in your inner voice.',
    reverseMeaning: 'Ignored intuition, secrets withheld, or disconnection from inner wisdom.',
    keywords: ['intuition', 'mystery', 'subconscious'],
    korNormalMeaning: '직관과 숨겨진 지식, 내면의 목소리를 믿는 태도를 뜻합니다.',
    korReverseMeaning: '무시된 직관과 감춰진 비밀, 내면의 지혜와의 단절을 나타냅니다.',
    korKeywords: ['직관', '신비', '잠재의식'],
  },
  {
    id: 'major-3',
    name: 'The Empress',
    korName: '여황제',
    arcana: 'major',
    number: 3,
    normalMeaning: 'Abundance, nurturing, and creative or physical growth.',
    reverseMeaning: 'Creative block, dependence, or neglect of self-care.',
    keywords: ['abundance', 'nurturing', 'creativity'],
    korNormalMeaning: '풍요와 돌봄, 창조적이거나 물리적인 성장을 상징합니다.',
    korReverseMeaning: '창의력 정체나 의존, 자기 돌봄의 소홀함을 의미합니다.',
    korKeywords: ['풍요', '돌봄', '창조성'],
  },
  {
    id: 'major-4',
    name: 'The Emperor',
    korName: '황제',
    arcana: 'major',
    number: 4,
    normalMeaning: 'Structure, authority, and stable leadership built on discipline.',
    reverseMeaning: 'Rigidity, domination, or a lack of healthy boundaries.',
    keywords: ['authority', 'structure', 'stability'],
    korNormalMeaning: '규율에 기반한 안정적인 리더십과 구조, 권위를 뜻합니다.',
    korReverseMeaning: '경직됨과 지배욕, 건강한 경계의 부재를 나타냅니다.',
    korKeywords: ['권위', '구조', '안정'],
  },
  {
    id: 'major-5',
    name: 'The Hierophant',
    korName: '교황',
    arcana: 'major',
    number: 5,
    normalMeaning: 'Tradition, guidance, and shared values within a community.',
    reverseMeaning: 'Questioning convention, unconventional paths, or rebellion against norms.',
    keywords: ['tradition', 'guidance', 'belief'],
    korNormalMeaning: '전통과 가르침, 공동체 안에서 공유되는 가치를 의미합니다.',
    korReverseMeaning: '관습에 대한 의문, 틀을 벗어난 길이나 반항을 뜻합니다.',
    korKeywords: ['전통', '가르침', '신념'],
  },
  {
    id: 'major-6',
    name: 'The Lovers',
    korName: '연인',
    arcana: 'major',
    number: 6,
    normalMeaning: 'Deep connection, meaningful choices, and alignment of values.',
    reverseMeaning: 'Misalignment, indecision, or imbalance in a relationship.',
    keywords: ['connection', 'choice', 'harmony'],
    korNormalMeaning: '깊은 유대와 의미 있는 선택, 가치관의 일치를 나타냅니다.',
    korReverseMeaning: '어긋남과 우유부단, 관계 속 불균형을 의미합니다.',
    korKeywords: ['유대', '선택', '조화'],
  },
  {
    id: 'major-7',
    name: 'The Chariot',
    korName: '전차',
    arcana: 'major',
    number: 7,
    normalMeaning: 'Determination, willpower, and victory through focused effort.',
    reverseMeaning: 'Lack of direction, loss of control, or aggressive pushing forward.',
    keywords: ['determination', 'willpower', 'victory'],
    korNormalMeaning: '결단력과 의지, 집중된 노력으로 얻는 승리를 뜻합니다.',
    korReverseMeaning: '방향성 상실과 통제력 부재, 무리한 밀어붙임을 나타냅니다.',
    korKeywords: ['결단력', '의지', '승리'],
  },
  {
    id: 'major-8',
    name: 'Strength',
    korName: '힘',
    arcana: 'major',
    number: 8,
    normalMeaning: 'Inner courage, compassion, and calm mastery over difficulty.',
    reverseMeaning: 'Self-doubt, insecurity, or a struggle with inner impulses.',
    keywords: ['courage', 'patience', 'inner strength'],
    korNormalMeaning: '내면의 용기와 연민, 어려움을 다스리는 차분한 힘을 의미합니다.',
    korReverseMeaning: '자기 의심과 불안, 내면의 충동과의 씨름을 뜻합니다.',
    korKeywords: ['용기', '인내', '내면의 힘'],
  },
  {
    id: 'major-9',
    name: 'The Hermit',
    korName: '은둔자',
    arcana: 'major',
    number: 9,
    normalMeaning: 'Introspection, solitude, and seeking guidance from within.',
    reverseMeaning: 'Isolation, withdrawal, or avoidance of needed self-reflection.',
    keywords: ['introspection', 'solitude', 'guidance'],
    korNormalMeaning: '성찰과 고독, 내면에서 답을 찾는 과정을 나타냅니다.',
    korReverseMeaning: '고립과 회피, 필요한 성찰을 미루는 태도를 의미합니다.',
    korKeywords: ['성찰', '고독', '안내'],
  },
  {
    id: 'major-10',
    name: 'Wheel of Fortune',
    korName: '운명의 수레바퀴',
    arcana: 'major',
    number: 10,
    normalMeaning: 'Cycles, turning points, and change driven by fate.',
    reverseMeaning: 'Resistance to change, bad timing, or a run of setbacks.',
    keywords: ['change', 'cycles', 'destiny'],
    korNormalMeaning: '순환과 전환점, 운명이 가져오는 변화를 뜻합니다.',
    korReverseMeaning: '변화에 대한 저항과 나쁜 타이밍, 연이은 시련을 나타냅니다.',
    korKeywords: ['변화', '순환', '운명'],
  },
  {
    id: 'major-11',
    name: 'Justice',
    korName: '정의',
    arcana: 'major',
    number: 11,
    normalMeaning: "Fairness, truth, and accountability for one's actions.",
    reverseMeaning: 'Unfairness, dishonesty, or avoidance of consequences.',
    keywords: ['fairness', 'truth', 'cause and effect'],
    korNormalMeaning: '공정함과 진실, 자신의 행동에 대한 책임을 의미합니다.',
    korReverseMeaning: '불공정함과 정직하지 못함, 결과를 회피하려는 태도를 뜻합니다.',
    korKeywords: ['공정함', '진실', '인과응보'],
  },
  {
    id: 'major-12',
    name: 'The Hanged Man',
    korName: '매달린 남자',
    arcana: 'major',
    number: 12,
    normalMeaning: 'A pause for new perspective, surrender, and letting go of control.',
    reverseMeaning: 'Stalling, resistance to change, or needless self-sacrifice.',
    keywords: ['surrender', 'new perspective', 'pause'],
    korNormalMeaning: '새로운 시각을 위한 멈춤과 내려놓음, 통제를 포기하는 것을 나타냅니다.',
    korReverseMeaning: '정체와 변화에 대한 저항, 불필요한 자기희생을 의미합니다.',
    korKeywords: ['내려놓음', '새로운 시각', '멈춤'],
  },
  {
    id: 'major-13',
    name: 'Death',
    korName: '죽음',
    arcana: 'major',
    number: 13,
    normalMeaning: 'Endings that make room for transformation and renewal.',
    reverseMeaning: 'Resistance to necessary change or fear of letting go.',
    keywords: ['transformation', 'endings', 'renewal'],
    korNormalMeaning: '변화와 재생을 위한 자리를 마련하는 끝맺음을 뜻합니다.',
    korReverseMeaning: '필요한 변화에 대한 저항이나 내려놓기에 대한 두려움을 나타냅니다.',
    korKeywords: ['변화', '끝맺음', '재생'],
  },
  {
    id: 'major-14',
    name: 'Temperance',
    korName: '절제',
    arcana: 'major',
    number: 14,
    normalMeaning: 'Balance, patience, and blending opposites into harmony.',
    reverseMeaning: 'Imbalance, excess, or impatience with a gradual process.',
    keywords: ['balance', 'moderation', 'patience'],
    korNormalMeaning: '균형과 인내, 상반된 것들을 조화롭게 섞는 태도를 의미합니다.',
    korReverseMeaning: '불균형과 과도함, 점진적인 과정에 대한 조급함을 뜻합니다.',
    korKeywords: ['균형', '절제', '인내'],
  },
  {
    id: 'major-15',
    name: 'The Devil',
    korName: '악마',
    arcana: 'major',
    number: 15,
    normalMeaning: 'Attachment, temptation, or patterns that feel hard to escape.',
    reverseMeaning: 'Breaking free from limiting habits or unhealthy attachments.',
    keywords: ['attachment', 'temptation', 'restriction'],
    korNormalMeaning: '집착과 유혹, 벗어나기 힘들게 느껴지는 패턴을 나타냅니다.',
    korReverseMeaning: '억눌린 습관이나 건강하지 못한 집착에서 벗어나는 것을 의미합니다.',
    korKeywords: ['집착', '유혹', '속박'],
  },
  {
    id: 'major-16',
    name: 'The Tower',
    korName: '탑',
    arcana: 'major',
    number: 16,
    normalMeaning: 'Sudden upheaval that breaks down what was built on a false foundation.',
    reverseMeaning: 'Averting disaster, delayed collapse, or fear of change.',
    keywords: ['upheaval', 'revelation', 'sudden change'],
    korNormalMeaning: '잘못된 토대 위에 세워진 것을 무너뜨리는 갑작스러운 격변을 뜻합니다.',
    korReverseMeaning: '재앙을 피하거나 붕괴가 지연됨, 변화에 대한 두려움을 나타냅니다.',
    korKeywords: ['격변', '깨달음', '급변'],
  },
  {
    id: 'major-17',
    name: 'The Star',
    korName: '별',
    arcana: 'major',
    number: 17,
    normalMeaning: 'Hope, healing, and quiet faith after a difficult period.',
    reverseMeaning: 'Discouragement, lost hope, or disconnection from purpose.',
    keywords: ['hope', 'healing', 'inspiration'],
    korNormalMeaning: '어려운 시기 이후 찾아오는 희망과 치유, 조용한 믿음을 의미합니다.',
    korReverseMeaning: '낙담과 상실된 희망, 목적과의 단절을 뜻합니다.',
    korKeywords: ['희망', '치유', '영감'],
  },
  {
    id: 'major-18',
    name: 'The Moon',
    korName: '달',
    arcana: 'major',
    number: 18,
    normalMeaning: "Uncertainty, intuition, and navigating what isn't fully clear.",
    reverseMeaning: 'Clarity emerging, released fear, or misread signals.',
    keywords: ['uncertainty', 'illusion', 'intuition'],
    korNormalMeaning: '불확실함과 직관, 아직 명확하지 않은 것들을 헤쳐나가는 과정을 나타냅니다.',
    korReverseMeaning: '명료함이 드러나거나 두려움이 해소됨, 잘못 읽었던 신호를 의미합니다.',
    korKeywords: ['불확실성', '환상', '직관'],
  },
  {
    id: 'major-19',
    name: 'The Sun',
    korName: '태양',
    arcana: 'major',
    number: 19,
    normalMeaning: 'Joy, vitality, and clear, positive success.',
    reverseMeaning: 'Temporary clouds over happiness or unrealistic optimism.',
    keywords: ['joy', 'vitality', 'success'],
    korNormalMeaning: '기쁨과 활력, 분명하고 긍정적인 성공을 뜻합니다.',
    korReverseMeaning: '행복을 가리는 일시적인 그늘이나 비현실적인 낙관을 나타냅니다.',
    korKeywords: ['기쁨', '활력', '성공'],
  },
  {
    id: 'major-20',
    name: 'Judgement',
    korName: '심판',
    arcana: 'major',
    number: 20,
    normalMeaning: 'Reflection, awakening, and a call to a higher purpose.',
    reverseMeaning: 'Self-doubt, harsh self-judgment, or avoiding a needed reckoning.',
    keywords: ['awakening', 'reflection', 'renewal'],
    korNormalMeaning: '성찰과 각성, 더 높은 목적을 향한 부름을 의미합니다.',
    korReverseMeaning: '자기 의심과 지나친 자기 비판, 필요한 성찰을 회피하는 것을 뜻합니다.',
    korKeywords: ['각성', '성찰', '재생'],
  },
  {
    id: 'major-21',
    name: 'The World',
    korName: '세계',
    arcana: 'major',
    number: 21,
    normalMeaning: 'Completion, fulfillment, and successful integration of a journey.',
    reverseMeaning: 'Incompletion, delay, or a goal that is almost within reach.',
    keywords: ['completion', 'fulfillment', 'wholeness'],
    korNormalMeaning: '완성과 성취, 하나의 여정이 성공적으로 통합됨을 나타냅니다.',
    korReverseMeaning: '미완성과 지연, 거의 다다른 목표를 의미합니다.',
    korKeywords: ['완성', '성취', '완전함'],
  },
];

// ============================================================
// Minor Arcana — Wands (14장, 불 / 행동·열정·커리어)
// ============================================================
const WANDS: TarotCard[] = [
  {
    id: 'wands-1',
    name: 'Ace of Wands',
    korName: '완드 에이스',
    arcana: 'minor',
    suit: 'wands',
    number: 1,
    normalMeaning: 'A spark of inspiration and the raw energy to start something new.',
    reverseMeaning: 'Delays, lack of motivation, or an idea that fizzles before it starts.',
    keywords: ['inspiration', 'new venture', 'energy'],
    korNormalMeaning: '새로운 것을 시작할 영감과 순수한 에너지가 샘솟는 순간을 뜻합니다.',
    korReverseMeaning: '지연이나 의욕 저하, 시작하기도 전에 사그라드는 아이디어를 나타냅니다.',
    korKeywords: ['영감', '새로운 도전', '에너지'],
  },
  {
    id: 'wands-2',
    name: 'Two of Wands',
    korName: '완드 2',
    arcana: 'minor',
    suit: 'wands',
    number: 2,
    normalMeaning: 'Planning ahead and weighing options before taking a bold step.',
    reverseMeaning: 'Hesitation, fear of the unknown, or a lack of clear planning.',
    keywords: ['planning', 'decision', 'future vision'],
    korNormalMeaning: '과감한 한 걸음을 내딛기 전에 미리 계획하고 선택지를 저울질하는 것을 의미합니다.',
    korReverseMeaning: '망설임과 미지에 대한 두려움, 명확한 계획의 부재를 뜻합니다.',
    korKeywords: ['계획', '결정', '미래에 대한 비전'],
  },
  {
    id: 'wands-3',
    name: 'Three of Wands',
    korName: '완드 3',
    arcana: 'minor',
    suit: 'wands',
    number: 3,
    normalMeaning: 'Expansion, foresight, and progress after initial groundwork.',
    reverseMeaning: 'Delays in plans or obstacles slowing anticipated growth.',
    keywords: ['expansion', 'foresight', 'progress'],
    korNormalMeaning: '기초 작업 이후 찾아오는 확장과 통찰력, 진전을 나타냅니다.',
    korReverseMeaning: '계획의 지연이나 기대했던 성장을 가로막는 장애물을 의미합니다.',
    korKeywords: ['확장', '통찰력', '진전'],
  },
  {
    id: 'wands-4',
    name: 'Four of Wands',
    korName: '완드 4',
    arcana: 'minor',
    suit: 'wands',
    number: 4,
    normalMeaning: 'Celebration, stability, and a sense of homecoming or achievement.',
    reverseMeaning: 'Instability at home or a celebration postponed.',
    keywords: ['celebration', 'stability', 'harmony'],
    korNormalMeaning: '축하와 안정감, 귀향이나 성취의 느낌을 뜻합니다.',
    korReverseMeaning: '가정의 불안정이나 미뤄진 축하를 나타냅니다.',
    korKeywords: ['축하', '안정', '화합'],
  },
  {
    id: 'wands-5',
    name: 'Five of Wands',
    korName: '완드 5',
    arcana: 'minor',
    suit: 'wands',
    number: 5,
    normalMeaning: 'Competition, friction, and conflicting ideas that need resolving.',
    reverseMeaning: 'Avoiding conflict or unresolved tension coming to a head.',
    keywords: ['conflict', 'competition', 'tension'],
    korNormalMeaning: '경쟁과 마찰, 풀어야 할 상충되는 의견들을 의미합니다.',
    korReverseMeaning: '갈등을 회피하거나 해소되지 않은 긴장이 곪아가는 것을 뜻합니다.',
    korKeywords: ['갈등', '경쟁', '긴장'],
  },
  {
    id: 'wands-6',
    name: 'Six of Wands',
    korName: '완드 6',
    arcana: 'minor',
    suit: 'wands',
    number: 6,
    normalMeaning: 'Recognition, victory, and public acknowledgment of effort.',
    reverseMeaning: 'Delayed recognition or doubt about a hard-won success.',
    keywords: ['victory', 'recognition', 'confidence'],
    korNormalMeaning: '인정과 승리, 노력에 대한 공개적인 인정을 나타냅니다.',
    korReverseMeaning: '지연된 인정이나 힘겹게 얻은 성공에 대한 의심을 의미합니다.',
    korKeywords: ['승리', '인정', '자신감'],
  },
  {
    id: 'wands-7',
    name: 'Seven of Wands',
    korName: '완드 7',
    arcana: 'minor',
    suit: 'wands',
    number: 7,
    normalMeaning: 'Standing your ground and defending your position under pressure.',
    reverseMeaning: 'Feeling overwhelmed or giving up a position too easily.',
    keywords: ['perseverance', 'defense', 'resilience'],
    korNormalMeaning: '압박 속에서도 자신의 입장을 지키고 방어하는 것을 뜻합니다.',
    korReverseMeaning: '압도당하는 느낌이나 자신의 입지를 너무 쉽게 포기하는 것을 나타냅니다.',
    korKeywords: ['인내', '방어', '회복력'],
  },
  {
    id: 'wands-8',
    name: 'Eight of Wands',
    korName: '완드 8',
    arcana: 'minor',
    suit: 'wands',
    number: 8,
    normalMeaning: 'Fast-moving momentum and swift developments coming together.',
    reverseMeaning: 'Delays, frustration, or plans that stall unexpectedly.',
    keywords: ['momentum', 'speed', 'movement'],
    korNormalMeaning: '빠르게 진행되는 흐름과 신속한 전개가 한꺼번에 몰려오는 것을 의미합니다.',
    korReverseMeaning: '지연이나 좌절, 예상치 못하게 멈춰버린 계획을 뜻합니다.',
    korKeywords: ['속도', '추진력', '움직임'],
  },
  {
    id: 'wands-9',
    name: 'Nine of Wands',
    korName: '완드 9',
    arcana: 'minor',
    suit: 'wands',
    number: 9,
    normalMeaning: 'Resilience and guarded strength after facing repeated challenges.',
    reverseMeaning: 'Exhaustion, burnout, or being overly defensive.',
    keywords: ['resilience', 'persistence', 'caution'],
    korNormalMeaning: '반복된 시련을 겪은 뒤에도 지키는 회복력과 경계심을 나타냅니다.',
    korReverseMeaning: '소진이나 번아웃, 지나치게 방어적인 태도를 의미합니다.',
    korKeywords: ['회복력', '끈기', '경계'],
  },
  {
    id: 'wands-10',
    name: 'Ten of Wands',
    korName: '완드 10',
    arcana: 'minor',
    suit: 'wands',
    number: 10,
    normalMeaning: 'Carrying a heavy load of responsibility near the finish line.',
    reverseMeaning: 'Overwhelm, burnout, or the need to delegate a burden.',
    keywords: ['burden', 'responsibility', 'overwhelm'],
    korNormalMeaning: '결승선을 앞두고 짊어진 무거운 책임의 짐을 뜻합니다.',
    korReverseMeaning: '압도감이나 번아웃, 짐을 나눠야 할 필요성을 나타냅니다.',
    korKeywords: ['부담', '책임', '압박감'],
  },
  {
    id: 'wands-11',
    name: 'Page of Wands',
    korName: '완드 페이지',
    arcana: 'minor',
    suit: 'wands',
    number: 11,
    normalMeaning: 'Curiosity and enthusiasm for exploring a new passion or idea.',
    reverseMeaning: 'Scattered energy or hesitation to commit to a new interest.',
    keywords: ['curiosity', 'enthusiasm', 'exploration'],
    korNormalMeaning: '새로운 열정이나 아이디어를 탐구하려는 호기심과 열의를 의미합니다.',
    korReverseMeaning: '산만한 에너지나 새로운 관심사에 전념하기를 망설이는 태도를 뜻합니다.',
    korKeywords: ['호기심', '열정', '탐구'],
  },
  {
    id: 'wands-12',
    name: 'Knight of Wands',
    korName: '완드 기사',
    arcana: 'minor',
    suit: 'wands',
    number: 12,
    normalMeaning: 'Bold action, confidence, and a passionate pursuit of a goal.',
    reverseMeaning: 'Impulsiveness, recklessness, or a project started without follow-through.',
    keywords: ['boldness', 'passion', 'impulsiveness'],
    korNormalMeaning: '목표를 향한 과감한 행동과 자신감, 열정적인 추진력을 나타냅니다.',
    korReverseMeaning: '충동적이거나 무모한 행동, 끝맺음 없이 시작만 하는 프로젝트를 의미합니다.',
    korKeywords: ['대담함', '열정', '충동성'],
  },
  {
    id: 'wands-13',
    name: 'Queen of Wands',
    korName: '완드 여왕',
    arcana: 'minor',
    suit: 'wands',
    number: 13,
    normalMeaning: 'Confident warmth, independence, and magnetic self-assurance.',
    reverseMeaning: 'Insecurity, jealousy, or forced confidence covering self-doubt.',
    keywords: ['confidence', 'independence', 'warmth'],
    korNormalMeaning: '자신감 있는 따뜻함과 독립심, 매력적인 자기 확신을 뜻합니다.',
    korReverseMeaning: '불안정함이나 질투, 자기 의심을 감추려는 억지스러운 자신감을 나타냅니다.',
    korKeywords: ['자신감', '독립심', '따뜻함'],
  },
  {
    id: 'wands-14',
    name: 'King of Wands',
    korName: '완드 왕',
    arcana: 'minor',
    suit: 'wands',
    number: 14,
    normalMeaning: 'Visionary leadership and bold, confident direction.',
    reverseMeaning: 'Overbearing ambition or impulsive decisions without follow-through.',
    keywords: ['leadership', 'vision', 'boldness'],
    korNormalMeaning: '비전 있는 리더십과 대담하고 확신에 찬 방향 제시를 의미합니다.',
    korReverseMeaning: '지나친 야망이나 끝맺음 없는 충동적인 결정을 뜻합니다.',
    korKeywords: ['리더십', '비전', '대담함'],
  },
];

// ============================================================
// Minor Arcana — Cups (14장, 물 / 감정·관계)
// ============================================================
const CUPS: TarotCard[] = [
  {
    id: 'cups-1',
    name: 'Ace of Cups',
    korName: '컵 에이스',
    arcana: 'minor',
    suit: 'cups',
    number: 1,
    normalMeaning: 'A new wave of emotional openness, love, or intuitive connection.',
    reverseMeaning: 'Emotional blockage, holding back feelings, or a missed connection.',
    keywords: ['new feelings', 'love', 'intuition'],
    korNormalMeaning: '감정적으로 마음을 열고 사랑이나 직관적인 연결이 새롭게 밀려오는 것을 나타냅니다.',
    korReverseMeaning: '감정의 억제나 마음을 닫는 것, 놓쳐버린 인연을 의미합니다.',
    korKeywords: ['새로운 감정', '사랑', '직관'],
  },
  {
    id: 'cups-2',
    name: 'Two of Cups',
    korName: '컵 2',
    arcana: 'minor',
    suit: 'cups',
    number: 2,
    normalMeaning: 'Mutual connection, partnership, and emotional balance between two people.',
    reverseMeaning: 'Imbalance in a relationship or a connection that has cooled.',
    keywords: ['partnership', 'connection', 'mutual respect'],
    korNormalMeaning: '두 사람 사이의 상호 연결과 파트너십, 감정적 균형을 뜻합니다.',
    korReverseMeaning: '관계 속 불균형이나 식어버린 관계를 나타냅니다.',
    korKeywords: ['파트너십', '연결', '상호 존중'],
  },
  {
    id: 'cups-3',
    name: 'Three of Cups',
    korName: '컵 3',
    arcana: 'minor',
    suit: 'cups',
    number: 3,
    normalMeaning: 'Celebration, friendship, and joyful shared community.',
    reverseMeaning: 'Overindulgence or friction within a social group.',
    keywords: ['friendship', 'celebration', 'community'],
    korNormalMeaning: '축하와 우정, 즐거운 공동체 안에서의 기쁨을 의미합니다.',
    korReverseMeaning: '지나친 탐닉이나 모임 안에서의 갈등을 뜻합니다.',
    korKeywords: ['우정', '축하', '공동체'],
  },
  {
    id: 'cups-4',
    name: 'Four of Cups',
    korName: '컵 4',
    arcana: 'minor',
    suit: 'cups',
    number: 4,
    normalMeaning: 'Emotional withdrawal or reevaluating what truly feels satisfying.',
    reverseMeaning: 'Renewed openness after a period of apathy or disengagement.',
    keywords: ['apathy', 'reevaluation', 'introspection'],
    korNormalMeaning: '감정적인 무관심이나 진정으로 만족스러운 것이 무엇인지 다시 돌아보는 것을 나타냅니다.',
    korReverseMeaning: '무관심한 시기를 지나 다시 마음을 여는 것을 의미합니다.',
    korKeywords: ['무관심', '재평가', '성찰'],
  },
  {
    id: 'cups-5',
    name: 'Five of Cups',
    korName: '컵 5',
    arcana: 'minor',
    suit: 'cups',
    number: 5,
    normalMeaning: 'Grief or disappointment while overlooking what still remains.',
    reverseMeaning: 'Acceptance and moving forward after a loss or setback.',
    keywords: ['loss', 'regret', 'moving on'],
    korNormalMeaning: '여전히 남아있는 것을 보지 못한 채 슬픔이나 실망에 잠기는 것을 뜻합니다.',
    korReverseMeaning: '상실이나 좌절을 딛고 받아들이며 앞으로 나아가는 것을 나타냅니다.',
    korKeywords: ['상실', '후회', '앞으로 나아가기'],
  },
  {
    id: 'cups-6',
    name: 'Six of Cups',
    korName: '컵 6',
    arcana: 'minor',
    suit: 'cups',
    number: 6,
    normalMeaning: 'Nostalgia, warmth, and comfort found in familiar memories.',
    reverseMeaning: 'Living in the past or an unhealthy attachment to nostalgia.',
    keywords: ['nostalgia', 'comfort', 'memories'],
    korNormalMeaning: '향수와 따뜻함, 익숙한 추억 속에서 느끼는 편안함을 의미합니다.',
    korReverseMeaning: '과거에 머무르거나 향수에 대한 건강하지 못한 집착을 뜻합니다.',
    korKeywords: ['향수', '편안함', '추억'],
  },
  {
    id: 'cups-7',
    name: 'Seven of Cups',
    korName: '컵 7',
    arcana: 'minor',
    suit: 'cups',
    number: 7,
    normalMeaning: 'Many options and daydreams that require clearer discernment.',
    reverseMeaning: 'Clarity replacing confusion, or facing an illusion honestly.',
    keywords: ['choices', 'imagination', 'illusion'],
    korNormalMeaning: '여러 선택지와 백일몽, 더 명확한 분별력이 필요한 상황을 나타냅니다.',
    korReverseMeaning: '혼란이 걷히고 명료해지거나 환상을 솔직하게 마주하는 것을 의미합니다.',
    korKeywords: ['선택', '상상력', '환상'],
  },
  {
    id: 'cups-8',
    name: 'Eight of Cups',
    korName: '컵 8',
    arcana: 'minor',
    suit: 'cups',
    number: 8,
    normalMeaning: 'Walking away from something unfulfilling to seek deeper meaning.',
    reverseMeaning: 'Fear of moving on or returning to a situation left behind.',
    keywords: ['walking away', 'seeking meaning', 'closure'],
    korNormalMeaning: '더 깊은 의미를 찾아 만족스럽지 않은 것을 떠나는 것을 뜻합니다.',
    korReverseMeaning: '떠나는 것에 대한 두려움이나 남겨두었던 상황으로 되돌아가는 것을 나타냅니다.',
    korKeywords: ['떠남', '의미 찾기', '마무리'],
  },
  {
    id: 'cups-9',
    name: 'Nine of Cups',
    korName: '컵 9',
    arcana: 'minor',
    suit: 'cups',
    number: 9,
    normalMeaning: 'Contentment, satisfaction, and emotional fulfillment.',
    reverseMeaning: 'Overindulgence or a hollow sense of satisfaction.',
    keywords: ['contentment', 'satisfaction', 'gratitude'],
    korNormalMeaning: '만족감과 충족, 정서적인 풍요로움을 의미합니다.',
    korReverseMeaning: '지나친 탐닉이나 공허한 만족감을 뜻합니다.',
    korKeywords: ['만족', '충족', '감사'],
  },
  {
    id: 'cups-10',
    name: 'Ten of Cups',
    korName: '컵 10',
    arcana: 'minor',
    suit: 'cups',
    number: 10,
    normalMeaning: 'Lasting happiness, harmony, and emotional fulfillment with loved ones.',
    reverseMeaning: 'Disconnection at home or a fragile sense of harmony.',
    keywords: ['harmony', 'fulfillment', 'togetherness'],
    korNormalMeaning: '사랑하는 사람들과 함께하는 지속적인 행복과 조화, 정서적 충만함을 나타냅니다.',
    korReverseMeaning: '가정 안의 단절이나 깨지기 쉬운 화합을 의미합니다.',
    korKeywords: ['화합', '충만함', '유대감'],
  },
  {
    id: 'cups-11',
    name: 'Page of Cups',
    korName: '컵 페이지',
    arcana: 'minor',
    suit: 'cups',
    number: 11,
    normalMeaning: 'Emotional curiosity and openness to a new, gentle beginning.',
    reverseMeaning: 'Emotional immaturity or being overly sensitive to setbacks.',
    keywords: ['curiosity', 'sensitivity', 'new feelings'],
    korNormalMeaning: '감정적인 호기심과 부드럽고 새로운 시작에 대한 열린 마음을 뜻합니다.',
    korReverseMeaning: '정서적인 미숙함이나 작은 일에도 지나치게 예민해지는 것을 나타냅니다.',
    korKeywords: ['호기심', '감수성', '새로운 감정'],
  },
  {
    id: 'cups-12',
    name: 'Knight of Cups',
    korName: '컵 기사',
    arcana: 'minor',
    suit: 'cups',
    number: 12,
    normalMeaning: 'A romantic, idealistic pursuit guided by the heart.',
    reverseMeaning: "Moodiness, unrealistic expectations, or an offer that isn't sincere.",
    keywords: ['romance', 'idealism', 'emotion-led action'],
    korNormalMeaning: '마음이 이끄는 대로 따르는 낭만적이고 이상적인 추구를 의미합니다.',
    korReverseMeaning: '변덕스러움이나 비현실적인 기대, 진심이 담기지 않은 제안을 뜻합니다.',
    korKeywords: ['낭만', '이상주의', '감정적 행동'],
  },
  {
    id: 'cups-13',
    name: 'Queen of Cups',
    korName: '컵 여왕',
    arcana: 'minor',
    suit: 'cups',
    number: 13,
    normalMeaning: 'Compassion, emotional depth, and intuitive care for others.',
    reverseMeaning: 'Emotional overwhelm or difficulty setting healthy boundaries.',
    keywords: ['compassion', 'intuition', 'emotional depth'],
    korNormalMeaning: '연민과 정서적 깊이, 타인을 향한 직관적인 돌봄을 나타냅니다.',
    korReverseMeaning: '감정적으로 벅차오르거나 건강한 경계를 세우기 어려운 상태를 의미합니다.',
    korKeywords: ['연민', '직관', '정서적 깊이'],
  },
  {
    id: 'cups-14',
    name: 'King of Cups',
    korName: '컵 왕',
    arcana: 'minor',
    suit: 'cups',
    number: 14,
    normalMeaning: 'Calm emotional mastery and balanced, compassionate leadership.',
    reverseMeaning: 'Moodiness or emotional manipulation beneath a calm surface.',
    keywords: ['emotional balance', 'compassion', 'maturity'],
    korNormalMeaning: '차분한 감정적 성숙함과 균형 잡힌 연민 어린 리더십을 뜻합니다.',
    korReverseMeaning: '겉으로는 차분해 보이지만 감정적으로 변덕스럽거나 조종하려는 태도를 나타냅니다.',
    korKeywords: ['감정적 균형', '연민', '성숙함'],
  },
];

// ============================================================
// Minor Arcana — Swords (14장, 공기 / 생각·갈등·진실)
// ============================================================
const SWORDS: TarotCard[] = [
  {
    id: 'swords-1',
    name: 'Ace of Swords',
    korName: '소드 에이스',
    arcana: 'minor',
    suit: 'swords',
    number: 1,
    normalMeaning: 'A moment of mental clarity and a breakthrough new idea.',
    reverseMeaning: 'Confusion, miscommunication, or a clouded decision.',
    keywords: ['clarity', 'breakthrough', 'truth'],
    korNormalMeaning: '정신이 명료해지는 순간과 돌파구가 되는 새로운 생각을 의미합니다.',
    korReverseMeaning: '혼란이나 의사소통의 오류, 흐려진 판단을 뜻합니다.',
    korKeywords: ['명료함', '돌파구', '진실'],
  },
  {
    id: 'swords-2',
    name: 'Two of Swords',
    korName: '소드 2',
    arcana: 'minor',
    suit: 'swords',
    number: 2,
    normalMeaning: 'A difficult decision made by carefully weighing both sides.',
    reverseMeaning: 'Avoidance of a decision or information kept hidden.',
    keywords: ['indecision', 'balance', 'stalemate'],
    korNormalMeaning: '양쪽을 신중하게 저울질하며 내리는 어려운 결정을 나타냅니다.',
    korReverseMeaning: '결정을 회피하거나 정보를 숨기는 것을 의미합니다.',
    korKeywords: ['우유부단', '균형', '교착 상태'],
  },
  {
    id: 'swords-3',
    name: 'Three of Swords',
    korName: '소드 3',
    arcana: 'minor',
    suit: 'swords',
    number: 3,
    normalMeaning: 'Heartbreak or a painful truth that must be faced honestly.',
    reverseMeaning: 'Healing from past pain or releasing old heartache.',
    keywords: ['heartbreak', 'grief', 'honesty'],
    korNormalMeaning: '정직하게 마주해야 할 마음의 상처나 아픈 진실을 뜻합니다.',
    korReverseMeaning: '지난 아픔을 치유하거나 오래된 상처를 흘려보내는 것을 나타냅니다.',
    korKeywords: ['상심', '슬픔', '솔직함'],
  },
  {
    id: 'swords-4',
    name: 'Four of Swords',
    korName: '소드 4',
    arcana: 'minor',
    suit: 'swords',
    number: 4,
    normalMeaning: 'Rest, recovery, and a needed pause before moving forward.',
    reverseMeaning: 'Burnout from refusing to rest or restlessness during recovery.',
    keywords: ['rest', 'recovery', 'reflection'],
    korNormalMeaning: '앞으로 나아가기 전에 필요한 휴식과 회복, 잠깐의 멈춤을 의미합니다.',
    korReverseMeaning: '쉬기를 거부해서 오는 번아웃이나 회복 중의 불안함을 뜻합니다.',
    korKeywords: ['휴식', '회복', '성찰'],
  },
  {
    id: 'swords-5',
    name: 'Five of Swords',
    korName: '소드 5',
    arcana: 'minor',
    suit: 'swords',
    number: 5,
    normalMeaning: 'Conflict where winning comes at the cost of goodwill.',
    reverseMeaning: 'Reconciliation or the fallout of a hollow victory.',
    keywords: ['conflict', 'tension', 'hollow victory'],
    korNormalMeaning: '이기더라도 호의를 잃게 되는 갈등을 나타냅니다.',
    korReverseMeaning: '화해나 공허한 승리 이후에 남는 여파를 의미합니다.',
    korKeywords: ['갈등', '긴장', '공허한 승리'],
  },
  {
    id: 'swords-6',
    name: 'Six of Swords',
    korName: '소드 6',
    arcana: 'minor',
    suit: 'swords',
    number: 6,
    normalMeaning: 'Moving away from difficulty toward calmer, clearer circumstances.',
    reverseMeaning: 'Feeling stuck or resisting a necessary transition.',
    keywords: ['transition', 'moving forward', 'relief'],
    korNormalMeaning: '어려움에서 벗어나 더 차분하고 명확한 상황으로 나아가는 것을 뜻합니다.',
    korReverseMeaning: '정체된 느낌이나 꼭 필요한 변화에 대한 저항을 나타냅니다.',
    korKeywords: ['이행', '전진', '안도감'],
  },
  {
    id: 'swords-7',
    name: 'Seven of Swords',
    korName: '소드 7',
    arcana: 'minor',
    suit: 'swords',
    number: 7,
    normalMeaning: 'Strategy, discretion, or acting without full transparency.',
    reverseMeaning: 'A hidden truth coming to light or guilt over a deception.',
    keywords: ['strategy', 'secrecy', 'discretion'],
    korNormalMeaning: '전략과 신중함, 완전히 투명하지 않은 채로 행동하는 것을 의미합니다.',
    korReverseMeaning: '숨겨졌던 진실이 드러나거나 속임수에 대한 죄책감을 뜻합니다.',
    korKeywords: ['전략', '은밀함', '신중함'],
  },
  {
    id: 'swords-8',
    name: 'Eight of Swords',
    korName: '소드 8',
    arcana: 'minor',
    suit: 'swords',
    number: 8,
    normalMeaning: 'Feeling trapped by self-imposed limits or restricted options.',
    reverseMeaning: 'Regaining freedom by challenging self-limiting beliefs.',
    keywords: ['restriction', 'self-doubt', 'limitation'],
    korNormalMeaning: '스스로 만든 한계나 제한된 선택지에 갇힌 느낌을 나타냅니다.',
    korReverseMeaning: '자기 제한적인 믿음에 도전하며 다시 자유를 되찾는 것을 의미합니다.',
    korKeywords: ['속박', '자기 의심', '제한'],
  },
  {
    id: 'swords-9',
    name: 'Nine of Swords',
    korName: '소드 9',
    arcana: 'minor',
    suit: 'swords',
    number: 9,
    normalMeaning: 'Anxiety and worry, often worse in the mind than in reality.',
    reverseMeaning: 'Relief after facing fears or releasing an anxious spiral.',
    keywords: ['anxiety', 'worry', 'overthinking'],
    korNormalMeaning: '불안과 걱정, 실제보다 마음속에서 더 크게 느껴지는 두려움을 뜻합니다.',
    korReverseMeaning: '두려움을 마주한 뒤 찾아오는 안도감이나 불안의 소용돌이에서 벗어나는 것을 나타냅니다.',
    korKeywords: ['불안', '걱정', '과도한 생각'],
  },
  {
    id: 'swords-10',
    name: 'Ten of Swords',
    korName: '소드 10',
    arcana: 'minor',
    suit: 'swords',
    number: 10,
    normalMeaning: 'A painful ending that clears the way for a genuine new start.',
    reverseMeaning: 'Slow recovery from a setback or resisting an inevitable ending.',
    keywords: ['ending', 'release', 'rock bottom'],
    korNormalMeaning: '진정으로 새롭게 시작할 길을 열어주는 고통스러운 끝맺음을 의미합니다.',
    korReverseMeaning: '시련에서 더디게 회복하거나 피할 수 없는 끝을 거부하는 것을 뜻합니다.',
    korKeywords: ['끝맺음', '해방', '바닥을 침'],
  },
  {
    id: 'swords-11',
    name: 'Page of Swords',
    korName: '소드 페이지',
    arcana: 'minor',
    suit: 'swords',
    number: 11,
    normalMeaning: 'Curious, alert thinking and eagerness to learn or communicate.',
    reverseMeaning: 'Gossip, scattered thoughts, or acting on incomplete information.',
    keywords: ['curiosity', 'alertness', 'communication'],
    korNormalMeaning: '호기심 가득하고 예리한 사고, 배우거나 소통하고자 하는 열의를 나타냅니다.',
    korReverseMeaning: '소문이나 산만한 생각, 불완전한 정보로 행동하는 것을 의미합니다.',
    korKeywords: ['호기심', '예리함', '소통'],
  },
  {
    id: 'swords-12',
    name: 'Knight of Swords',
    korName: '소드 기사',
    arcana: 'minor',
    suit: 'swords',
    number: 12,
    normalMeaning: 'Fast, decisive action driven by sharp, focused thinking.',
    reverseMeaning: 'Recklessness or pushing an agenda without considering consequences.',
    keywords: ['decisiveness', 'speed', 'directness'],
    korNormalMeaning: '날카롭고 집중된 사고에서 비롯된 빠르고 단호한 행동을 뜻합니다.',
    korReverseMeaning: '결과를 고려하지 않은 무모함이나 일방적인 밀어붙임을 나타냅니다.',
    korKeywords: ['결단력', '신속함', '직설적임'],
  },
  {
    id: 'swords-13',
    name: 'Queen of Swords',
    korName: '소드 여왕',
    arcana: 'minor',
    suit: 'swords',
    number: 13,
    normalMeaning: 'Clear-eyed honesty and independent, discerning judgment.',
    reverseMeaning: 'Coldness or overly harsh criticism toward others.',
    keywords: ['clarity', 'honesty', 'independence'],
    korNormalMeaning: '명료한 통찰에서 나오는 솔직함과 독립적이고 분별력 있는 판단을 의미합니다.',
    korReverseMeaning: '냉정함이나 타인에 대한 지나치게 가혹한 비판을 뜻합니다.',
    korKeywords: ['명료함', '솔직함', '독립성'],
  },
  {
    id: 'swords-14',
    name: 'King of Swords',
    korName: '소드 왕',
    arcana: 'minor',
    suit: 'swords',
    number: 14,
    normalMeaning: 'Rational authority and clear, principled decision-making.',
    reverseMeaning: 'Rigid logic or the misuse of power and authority.',
    keywords: ['authority', 'logic', 'principle'],
    korNormalMeaning: '이성적인 권위와 명확하고 원칙에 따른 의사결정을 나타냅니다.',
    korReverseMeaning: '경직된 논리나 권력의 오용을 의미합니다.',
    korKeywords: ['권위', '논리', '원칙'],
  },
];

// ============================================================
// Minor Arcana — Pentacles (14장, 흙 / 일·돈·물질)
// ============================================================
const PENTACLES: TarotCard[] = [
  {
    id: 'pentacles-1',
    name: 'Ace of Pentacles',
    korName: '펜타클 에이스',
    arcana: 'minor',
    suit: 'pentacles',
    number: 1,
    normalMeaning: 'A new opportunity for material growth, work, or stability.',
    reverseMeaning: 'A missed opportunity or an unstable, poorly planned start.',
    keywords: ['opportunity', 'stability', 'new venture'],
    korNormalMeaning: '물질적 성장이나 일, 안정을 향한 새로운 기회를 뜻합니다.',
    korReverseMeaning: '놓쳐버린 기회나 제대로 계획되지 않은 불안정한 시작을 나타냅니다.',
    korKeywords: ['기회', '안정', '새로운 시작'],
  },
  {
    id: 'pentacles-2',
    name: 'Two of Pentacles',
    korName: '펜타클 2',
    arcana: 'minor',
    suit: 'pentacles',
    number: 2,
    normalMeaning: 'Balancing multiple priorities with flexibility and good timing.',
    reverseMeaning: 'Overwhelm from too many demands or poor time management.',
    keywords: ['balance', 'adaptability', 'priorities'],
    korNormalMeaning: '유연함과 좋은 타이밍으로 여러 우선순위를 균형 있게 조율하는 것을 의미합니다.',
    korReverseMeaning: '너무 많은 요구에 압도되거나 시간 관리가 미흡한 상태를 뜻합니다.',
    korKeywords: ['균형', '적응력', '우선순위'],
  },
  {
    id: 'pentacles-3',
    name: 'Three of Pentacles',
    korName: '펜타클 3',
    arcana: 'minor',
    suit: 'pentacles',
    number: 3,
    normalMeaning: 'Collaboration and skilled teamwork building something of quality.',
    reverseMeaning: 'Poor teamwork or misaligned effort toward a shared goal.',
    keywords: ['teamwork', 'skill', 'collaboration'],
    korNormalMeaning: '협력과 숙련된 팀워크로 질 높은 결과물을 만들어가는 것을 나타냅니다.',
    korReverseMeaning: '서투른 팀워크나 공동의 목표를 향한 엇갈린 노력을 의미합니다.',
    korKeywords: ['팀워크', '숙련', '협업'],
  },
  {
    id: 'pentacles-4',
    name: 'Four of Pentacles',
    korName: '펜타클 4',
    arcana: 'minor',
    suit: 'pentacles',
    number: 4,
    normalMeaning: 'Security and control gained by holding tightly to resources.',
    reverseMeaning: 'Over-attachment to material things or fear of loss.',
    keywords: ['security', 'control', 'possessiveness'],
    korNormalMeaning: '자원을 꽉 붙잡음으로써 얻는 안정감과 통제감을 뜻합니다.',
    korReverseMeaning: '물질에 대한 지나친 집착이나 상실에 대한 두려움을 나타냅니다.',
    korKeywords: ['안정', '통제', '소유욕'],
  },
  {
    id: 'pentacles-5',
    name: 'Five of Pentacles',
    korName: '펜타클 5',
    arcana: 'minor',
    suit: 'pentacles',
    number: 5,
    normalMeaning: 'Hardship or feeling left out, with help closer than it seems.',
    reverseMeaning: 'Recovery from hardship or finding support after a hard time.',
    keywords: ['hardship', 'insecurity', 'isolation'],
    korNormalMeaning: '어려움이나 소외감을 느끼지만 도움은 생각보다 가까이 있음을 의미합니다.',
    korReverseMeaning: '고난을 딛고 회복하거나 힘든 시기 이후 지지를 얻는 것을 뜻합니다.',
    korKeywords: ['고난', '불안정', '소외감'],
  },
  {
    id: 'pentacles-6',
    name: 'Six of Pentacles',
    korName: '펜타클 6',
    arcana: 'minor',
    suit: 'pentacles',
    number: 6,
    normalMeaning: 'Generosity, fair exchange, and support given or received.',
    reverseMeaning: 'An imbalance of power in giving or receiving help.',
    keywords: ['generosity', 'balance', 'support'],
    korNormalMeaning: '관대함과 공정한 주고받음, 도움을 주고받는 것을 나타냅니다.',
    korReverseMeaning: '주고받는 관계에서의 힘의 불균형을 의미합니다.',
    korKeywords: ['관대함', '균형', '지원'],
  },
  {
    id: 'pentacles-7',
    name: 'Seven of Pentacles',
    korName: '펜타클 7',
    arcana: 'minor',
    suit: 'pentacles',
    number: 7,
    normalMeaning: "Patience while assessing the long-term results of past effort.",
    reverseMeaning: 'Impatience or frustration with slow, uncertain progress.',
    keywords: ['patience', 'assessment', 'long-term view'],
    korNormalMeaning: '지난 노력의 장기적인 결실을 평가하며 인내심을 갖는 것을 뜻합니다.',
    korReverseMeaning: '더디고 불확실한 진행 상황에 대한 조급함이나 답답함을 나타냅니다.',
    korKeywords: ['인내', '평가', '장기적 시각'],
  },
  {
    id: 'pentacles-8',
    name: 'Eight of Pentacles',
    korName: '펜타클 8',
    arcana: 'minor',
    suit: 'pentacles',
    number: 8,
    normalMeaning: 'Dedicated craftsmanship and steady focus on improving a skill.',
    reverseMeaning: 'Careless work or a lack of focus on quality.',
    keywords: ['diligence', 'skill-building', 'focus'],
    korNormalMeaning: '헌신적인 장인정신과 실력을 갈고닦는 데 쏟는 꾸준한 집중을 의미합니다.',
    korReverseMeaning: '부주의한 작업이나 품질에 대한 관심 부족을 뜻합니다.',
    korKeywords: ['성실함', '실력 향상', '집중'],
  },
  {
    id: 'pentacles-9',
    name: 'Nine of Pentacles',
    korName: '펜타클 9',
    arcana: 'minor',
    suit: 'pentacles',
    number: 9,
    normalMeaning: "Self-sufficiency and enjoying the rewards of one's own effort.",
    reverseMeaning: 'Overwork or financial insecurity despite outward appearances.',
    keywords: ['self-sufficiency', 'abundance', 'independence'],
    korNormalMeaning: '자립심과 스스로의 노력으로 얻은 결실을 누리는 것을 나타냅니다.',
    korReverseMeaning: '겉으로는 괜찮아 보여도 과로하거나 재정적으로 불안정한 상태를 의미합니다.',
    korKeywords: ['자립', '풍요', '독립심'],
  },
  {
    id: 'pentacles-10',
    name: 'Ten of Pentacles',
    korName: '펜타클 10',
    arcana: 'minor',
    suit: 'pentacles',
    number: 10,
    normalMeaning: 'Long-term security, legacy, and stability built over time.',
    reverseMeaning: 'Financial instability or disruption within family structures.',
    keywords: ['legacy', 'security', 'stability'],
    korNormalMeaning: '시간을 두고 쌓아온 장기적인 안정과 유산, 견고함을 뜻합니다.',
    korReverseMeaning: '재정적 불안정이나 가족 구조 안의 혼란을 나타냅니다.',
    korKeywords: ['유산', '안정', '견고함'],
  },
  {
    id: 'pentacles-11',
    name: 'Page of Pentacles',
    korName: '펜타클 페이지',
    arcana: 'minor',
    suit: 'pentacles',
    number: 11,
    normalMeaning: 'A practical new opportunity approached with curiosity and diligence.',
    reverseMeaning: 'Procrastination or unrealistic plans without solid follow-through.',
    keywords: ['opportunity', 'diligence', 'practicality'],
    korNormalMeaning: '호기심과 성실함으로 다가서는 현실적인 새로운 기회를 의미합니다.',
    korReverseMeaning: '뒷받침되지 않는 미루기나 비현실적인 계획을 뜻합니다.',
    korKeywords: ['기회', '성실함', '현실감각'],
  },
  {
    id: 'pentacles-12',
    name: 'Knight of Pentacles',
    korName: '펜타클 기사',
    arcana: 'minor',
    suit: 'pentacles',
    number: 12,
    normalMeaning: 'Steady, methodical progress through hard work and patience.',
    reverseMeaning: 'Stagnation or excessive caution that stalls progress.',
    keywords: ['diligence', 'reliability', 'steady progress'],
    korNormalMeaning: '성실한 노력과 인내를 통한 꾸준하고 체계적인 진전을 나타냅니다.',
    korReverseMeaning: '정체되거나 지나치게 신중해서 진전이 멈춘 상태를 의미합니다.',
    korKeywords: ['성실함', '신뢰성', '꾸준한 진전'],
  },
  {
    id: 'pentacles-13',
    name: 'Queen of Pentacles',
    korName: '펜타클 여왕',
    arcana: 'minor',
    suit: 'pentacles',
    number: 13,
    normalMeaning: 'Grounded nurturing and practical care for both people and resources.',
    reverseMeaning: 'Neglecting self-care while overextending for others.',
    keywords: ['nurturing', 'practicality', 'abundance'],
    korNormalMeaning: '사람과 자원을 실질적으로 돌보는 안정된 양육의 태도를 뜻합니다.',
    korReverseMeaning: '타인을 위해 너무 애쓰다 자기 자신을 돌보지 못하는 것을 나타냅니다.',
    korKeywords: ['돌봄', '현실감각', '풍요'],
  },
  {
    id: 'pentacles-14',
    name: 'King of Pentacles',
    korName: '펜타클 왕',
    arcana: 'minor',
    suit: 'pentacles',
    number: 14,
    normalMeaning: 'Steady, generous authority built on real-world success.',
    reverseMeaning: 'Materialism or stubbornness rooted in a fear of loss.',
    keywords: ['abundance', 'stability', 'generosity'],
    korNormalMeaning: '현실적인 성공을 바탕으로 한 안정되고 관대한 권위를 의미합니다.',
    korReverseMeaning: '물질주의나 상실에 대한 두려움에서 비롯된 고집스러움을 뜻합니다.',
    korKeywords: ['풍요', '안정', '관대함'],
  },
];

export const TAROT_CARDS: TarotCard[] = [
  ...MAJOR_ARCANA,
  ...WANDS,
  ...CUPS,
  ...SWORDS,
  ...PENTACLES,
];

export function getCardByName(name: string): TarotCard | undefined {
  return TAROT_CARDS.find((card) => card.name === name);
}

export function getRandomCards(count: number): TarotCard[] {
  const shuffled = [...TAROT_CARDS];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count);
}

export function getMajorArcana(): TarotCard[] {
  return TAROT_CARDS.filter((card) => card.arcana === 'major');
}

export function getMinorArcana(suit?: string): TarotCard[] {
  return TAROT_CARDS.filter(
    (card) => card.arcana === 'minor' && (suit ? card.suit === suit : true)
  );
}
